FROM node:18-alpine
WORKDIR /home/app
COPY package.json .
COPY nodemon.json .
COPY global.d.ts .
COPY .dockerignore .
COPY .eslintrc .
COPY .prettierrc .
COPY docker-compose.dev.yml .
COPY .gitignore .
COPY Dockerfile.dev .
COPY tsconfig.json .
COPY yarn.lock .
RUN yarn install
COPY ./prisma/schema.prisma ./prisma/
RUN yarn run database:generate
COPY . .
ENV PORT 3000
EXPOSE $PORT
CMD ["yarn", "dev"]