version: '3.9'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
      - "9229:9229"
    volumes:
      - .:/home/app:ro
      - /home/app/node_modules
    command: yarn dev
    environment:
      - PORT=3000
      - NODE_ENV=development